[theme]
base = "light"
primaryColor = "#1673E6"
backgroundColor = "#F7FAFE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#002B5C"
font = "sans serif"

[server]
headless = false

[browser]
gatherUsageStats = false
